name: meditationapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  go_router: ^14.3.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  jwt_decode: ^0.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  introduction_screen: ^3.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
